name: Code checkout
on:
  push:
    paths:
      - src/**
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for the presence of a compiler, install it if not
      run: |
        if ! cargo install --list | grep -q clue; then
          cargo install clue
        fi
    - name: Perform operations with the code
      run: |
        if ! grep -rnq 'print' ${{ github.workspace }}/src/; then
          bash ${{ github.workspace }}/build.sh debug
        fi
