name: Publish in release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Check for the presence of a compiler, install it if not
      run: cargo install --list | grep -q clue || cargo install clue
    - uses: actions/checkout@v2
    - name: Checkout code
      run: bash ${{ github.workspace }}/build.sh release && mv ${{ github.workspace }}/main.lua ${{ github.workspace }}/GAdmin-Release.lua
    - name: Upload release script
      uses: actions/upload-artifact@v4
      with:
        name: GAdmin-Release.lua
        path: ${{ github.workspace }}/GAdmin-Release.lua
    - name: Publish in release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: |
          ${{ github.workspace }}/GAdmin-Release.lua
